### PR TITLE
Work with more pythons

### PR DESCRIPTION
**Pull request by msabramo**
Builds on work in https://github.com/carlosescri/DottedDict/pull/2 and makes the tests pass on PyPy and Python 3 and adds a `.travis.yml` for Travis CI.

```
$ tox
...
  py26: commands succeeded
  py27: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  pypy: commands succeeded
  pypy3: commands succeeded
  cover: commands succeeded
  congratulations :)
```

Passing Travis CI build: https://travis-ci.org/msabramo/DottedDict/builds/47388719

### CODE REVIEW

**Comment by carlosescri** [comment]
Thank you very much for all your work. It's nice to learn something new. I want to review your commits and, very probably, I will merge them tomorrow.

**Comment by carlosescri** [comment]
Merged.

**Comment by msabramo** [comment]
Cool! Thanks! Want to release a new version to PyPI?

https://pypi.python.org/pypi/dotted

**Comment by carlosescri** [comment]
Yes, I'm on it :smiley:

**Comment by carlosescri** [comment]
The new release is online. Thank you very much for your commits!

**Pull request closed without merging**
